name: Continuous Integration

on:
  push:
    branches:
      - '**'

jobs:

  lint:
    name: 'Lint'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: action/checkout@v3
      - name: Setup Go 1.18
        uses: actions/setup-go@v3
        with:
          go-version: '^1.18'
      - name: Run linter
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

  test:
    name: 'Test'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: action/checkout@v3
      - name: Setup Go 1.18
        uses: actions/setup-go@v3
        with:
          go-version: '^1.18'
      - name: Run tests
        run: make test

  checks-passed:
    name: 'Checks passed'
    needs:
      [
        lint,
        test
      ]
    runs-on: ubuntu-latest
    steps:
      - name: done
        run: echo "Checks passed"
